# Use new container infrastructure to enable caching
sudo: false

# Use OSX to by-pass issue with CouchDB PGP Key on Linux
os: osx

# Generic language, we provide our custom builds
language: generic

# Caching so the next build will be fast too.
cache:
  timeout: 1337
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.ghc
  - $TRAVIS_BUILD_DIR/.stack-work

# Only clone the repo's tip
git:
  depth: false

# Setup some global env variables
env:
  global:
  - PATH=$HOME/.local/bin:$PATH           # For binaries installed with stack
  - HOMEBREW_NO_AUTO_UPDATE=1             # Prevent Homebrea from spending 5 minutes upgrading itself
  - HOMEBREW_CACHE=$HOME/.local/Homebrew  # Relocate Homebrew's cache which it can actually be cached

# Desactivate builds on branches but `develop` (CI is still triggered by PRs)
branches:
  only:
  - master
  - develop

# Define custom set of stages
stages:
- snapshot
- tooling
- extra-dependencies
- hlint
- coverage

# Install foreign dependencies required by some modules below
before_install:
- brew install rocksdb

# Build snapshot & dependencies in different jobs. This copes with Travis limit of 50 minutes per job.
jobs:
  include:
  # Rebuild only the snapshot. Note that, when triggered, job-concurrency should be limited
  # to 1 and we might have to re-play the build multiple times in case it couldn't build
  # everything in one go.
  # Before kicking this action, it would also be advised to cleanup the entire cache. Note that
  # we have a custom snapshot which contains also all the extra deps for cardano-sl; this way,
  # we only have to build them once.
  - stage: snapshot
    if: commit_message =~ /ci@update lts/
    script:
    - mkdir -p $HOME/.local/bin
    - travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    - travis_wait 42 stack --no-terminal --install-ghc build --only-snapshot

  # Install some extra dependencies we use to compile or in the CI.
  # FIXME: Try to fit 'rocksdb' in there and find a way to cache it?
  - stage: tooling
    if: commit_message =~ /ci@update lts/
    script:
    - stack --no-terminal install cpphs
    - git clone https://github.com/rubik/stack-hpc-coveralls && cd stack-hpc-coveralls && git checkout 3d8352d5642ab214a7a574bd797880ae39595a44
    - "echo 'resolver: lts-11.13' > stack.yaml && stack install && stack clean"

  # Rebuild only the extra dependencies; mainly: cardano-sl. This isn't part of the custom
  # snapshot because we likely bumps the git hash reference more often  than other dependencies.
  # Still, we build that as a separate job and only triggers it when appropriated. It's cached
  # otherwise.
  - stage: extra-dependencies
    if: commit_message =~ /ci@update stack.yaml/
    script:
    - travis_wait 42 stack --no-terminal build --fast --only-dependencies

  # Run hlint
  - stage: hlint
    script:
      - curl -sL https://raw.github.com/ndmitchell/hlint/bea72e4e61da54ecd451590734d6e10423ead100/misc/travis.sh | sh -s . --cpp-define=__GLASGOW_HASKELL__=800 --cpp-define=x86_64_HOST_ARCH=1 --cpp-define=mingw32_HOST_OS=1

  # Run all tests with code coverage
  - stage: coverage
    script:
    - stack clean
    - travis_wait 42 stack --no-terminal test --fast --coverage --ghc-options=-optl-Wl,-dead_strip_dylibs
    - shc cardano-wallet wallet-unit-tests wallet-new-specs
    - stack clean

  # FIXME: Upload API doc automatically on each build against `develop` to `gh-pages`
  # - stage: api-doc
  #   if: branch = develop
  #   script:
  #   - travis_wait 42 stack --no-terminal build cardano-sl-wallet-new:exe:cardano-generate-swagger-file --fast --ghc-options=-optl-Wl,-dead_strip_dylibs
  #   - stack exec -- cardano-generate-swagger-file --target wallet@v1
  #   - git checkout gh-pages ...
  #   - ... upload 'swagger.json' to gh-pages
