resolver: ./cardano-sl.yaml
packages:
- .

extra-deps:
- git: https://github.com/input-output-hk/cardano-sl
  commit: 9fdb95647c20df4cb5ee79737ee763b12ef9874b
  subdirs:
    - acid-state-exts
    - binary
    - binary/test
    - chain
    - chain/test
    - client
    - cluster
    - core
    - core/test
    - crypto
    - crypto/test
    - db
    - infra
    - lib
    - mnemonic
    - networking
    - node
    - node-ipc
    - util
    - util/test
    - utxo
    - x509

- generic-lens-1.1.0.0
