resolver: ./cardano-sl.yaml
packages:
- .
- ../cardano-sl/acid-state-exts
- ../cardano-sl/binary
- ../cardano-sl/binary/test
- ../cardano-sl/chain
- ../cardano-sl/chain/test
- ../cardano-sl/client
- ../cardano-sl/cluster
- ../cardano-sl/core
- ../cardano-sl/core/test
- ../cardano-sl/crypto
- ../cardano-sl/crypto/test
- ../cardano-sl/db
- ../cardano-sl/infra
- ../cardano-sl/lib
- ../cardano-sl/mnemonic
- ../cardano-sl/networking
- ../cardano-sl/node
- ../cardano-sl/node-ipc
- ../cardano-sl/util
- ../cardano-sl/util/test
- ../cardano-sl/utxo
- ../cardano-sl/x509

extra-deps:
  # - git: https://github.com/input-output-hk/cardano-sl
  #   commit: f5c1894c012a1897cc596ed07fc3b0b378087c34
  #   subdirs:
  #     - acid-state-exts
  #     - binary
  #     - binary/test
  #     - chain
  #     - chain/test
  #     - client
  #     - cluster
  #     - core
  #     - core/test
  #     - crypto
  #     - crypto/test
  #     - db
  #     - infra
  #     - lib
  #     - mnemonic
  #     - networking
  #     - node
  #     - node-ipc
  #     - util
  #     - util/test
  #     - utxo
  #     - x509

- generic-lens-1.1.0.0
